import { Hotspot } from './types';

// Initial Seed Data provided in the prompt
export const INITIAL_DATA: Hotspot[] = [
  {
    "id": "1",
    "date": "2025-12-25",
    "day": "Kamis",
    "time_window": "Sore",
    "predicted_hour": "16:30",
    "origin": "Toko Tiga Jalan Jendral Ahmad Yani (Malabar)",
    "type": "Bike",
    "category": "Commercial",
    "lat": -6.9205,
    "lng": 107.6200,
    "zone": "Pusat Kota - Kosambi",
    "notes": "Area pertokoan ramai sore hari saat tutup toko/pulang kerja."
  },
  {
    "id": "2",
    "date": "2025-12-25",
    "day": "Kamis",
    "time_window": "Siang",
    "predicted_hour": "12:15",
    "origin": "Doublesteak Bengawan Jalan Bengawan (Cihapit)",
    "type": "Bike Delivery",
    "category": "Culinary",
    "lat": -6.9080,
    "lng": 107.6250,
    "zone": "Riau - Cihapit",
    "notes": "Spot kuliner, potensi orderan food tinggi saat jam makan siang."
  },
  {
    "id": "3",
    "date": "2025-12-25",
    "day": "Kamis",
    "time_window": "Pagi",
    "predicted_hour": "09:00",
    "origin": "RSJP Paramarta Jalan Soekarno Hatta (Binong)",
    "type": "Bike",
    "category": "Health/Office",
    "lat": -6.9380,
    "lng": 107.6450,
    "zone": "Soekarno Hatta - Binong",
    "notes": "Rumah sakit/perkantoran, ramai kunjungan pagi."
  },
  {
    "id": "4",
    "date": "2025-12-25",
    "day": "Kamis",
    "time_window": "Siang",
    "predicted_hour": "14:00",
    "origin": "Gerai Tiki 084 Martanegara Jalan Raa Martanegara",
    "type": "Bike Delivery",
    "category": "Logistics",
    "lat": -6.9320,
    "lng": 107.6300,
    "zone": "Turangga - Martanegara",
    "notes": "Logistik/Ekspedisi biasanya ramai pengiriman siang hari."
  },
  {
    "id": "6",
    "date": "2025-12-25",
    "day": "Kamis",
    "time_window": "Pagi",
    "predicted_hour": "08:00",
    "origin": "Jalan Cidurian Utara Gang Sukabakti 149 (Sukapura)",
    "type": "Bike",
    "category": "Residential",
    "lat": -6.9250,
    "lng": 107.6550,
    "zone": "Kiaracondong - Sukapura",
    "notes": "Area padat penduduk, orderan berangkat kerja/sekolah."
  },
  {
    "id": "11",
    "date": "2025-12-25",
    "day": "Kamis",
    "time_window": "Sore",
    "predicted_hour": "17:00",
    "origin": "Gudang Kopi dan Rey Cuci Motor Jalan Jatihandap Timur",
    "type": "Bike",
    "category": "Service/Hangout",
    "lat": -6.8955,
    "lng": 107.6610,
    "zone": "Jatihandap",
    "notes": "Spot santai sore atau ambil kendaraan setelah cuci."
  },
  {
    "id": "12",
    "date": "2025-12-24",
    "day": "Rabu",
    "time_window": "Malam",
    "predicted_hour": "19:30",
    "origin": "Jalan Cibadak 18 (Karang Anyar)",
    "type": "Bike Delivery",
    "category": "Culinary Night",
    "lat": -6.9220,
    "lng": 107.5980,
    "zone": "Pusat Kota - Cibadak",
    "notes": "Cibadak adalah pusat kuliner malam (Street Food) Bandung."
  },
  {
    "id": "14",
    "date": "2025-12-24",
    "day": "Rabu",
    "time_window": "Siang",
    "predicted_hour": "13:00",
    "origin": "Serunai Collection Jalan Caringin",
    "type": "Bike",
    "category": "Commercial",
    "lat": -6.9350,
    "lng": 107.5750,
    "zone": "Caringin - Holis",
    "notes": "Area tekstil/gudang, aktif jam kerja."
  },
  {
    "id": "23",
    "date": "2025-12-23",
    "day": "Selasa",
    "time_window": "Pagi",
    "predicted_hour": "08:30",
    "origin": "UPT Puskesmas Padasuka Kota Bandung",
    "type": "Bike Delivery",
    "category": "Health",
    "lat": -6.9020,
    "lng": 107.6520,
    "zone": "Cicaheum - Padasuka",
    "notes": "Layanan kesehatan ramai di pagi hari."
  },
  {
    "id": "27",
    "date": "2025-12-22",
    "day": "Senin",
    "time_window": "Malam",
    "predicted_hour": "19:00",
    "origin": "Seafood Kiloan Bang Bopak Cab Pahlawan",
    "type": "Bike",
    "category": "Culinary",
    "lat": -6.8980,
    "lng": 107.6360,
    "zone": "Pahlawan - Katamso",
    "notes": "Restoran seafood biasanya puncak keramaian saat makan malam."
  },
  {
    "id": "31",
    "date": "2025-12-21",
    "day": "Minggu",
    "time_window": "Siang",
    "predicted_hour": "11:00",
    "origin": "Jalan H. Ibrahim Adjie 72 (Kebonwaru)",
    "type": "Bike Delivery",
    "category": "Residential/Shop",
    "lat": -6.9150,
    "lng": 107.6420,
    "zone": "Kiaracondong - Kebonwaru",
    "notes": "Area transit padat."
  },
  {
    "id": "40",
    "date": "2025-12-20",
    "day": "Sabtu",
    "time_window": "Sore",
    "predicted_hour": "15:30",
    "origin": "Masjid Jami Nurul Falah Jalan Desa (Babakan Sari)",
    "type": "Bike Delivery",
    "category": "Residential",
    "lat": -6.9180,
    "lng": 107.6480,
    "zone": "Kiaracondong - Babakan Sari",
    "notes": "Aktivitas warga sore hari di kawasan padat."
  },
  {
    "id": "46",
    "date": "2025-12-19",
    "day": "Jumat",
    "time_window": "Siang",
    "predicted_hour": "13:00",
    "origin": "Pos Honda Jalan Psm (Sukapura)",
    "type": "Bike",
    "category": "Service",
    "lat": -6.9250,
    "lng": 107.6500,
    "zone": "Kiaracondong - Sukapura",
    "notes": "Bengkel/Pos sering ramai setelah Jumatan."
  },
  {
    "id": "52",
    "date": "2025-12-18",
    "day": "Kamis",
    "time_window": "Dini Hari",
    "predicted_hour": "04:30",
    "origin": "Cahaya Plastik Jalan Pasar Induk Caringin",
    "type": "Bike",
    "category": "Market",
    "lat": -6.9350,
    "lng": 107.5750,
    "zone": "Caringin",
    "notes": "Pasar Induk Caringin adalah hotspot Dini Hari (02:00 - 06:00)."
  },
  {
    "id": "54",
    "date": "2025-12-18",
    "day": "Kamis",
    "time_window": "Sore",
    "predicted_hour": "17:00",
    "origin": "PT. Tirta Makmur Mahkota Abadi Jalan Kavling Manglid X",
    "type": "Bike",
    "category": "Industrial/Office",
    "lat": -6.9650,
    "lng": 107.5900,
    "zone": "Margahayu",
    "notes": "Kawasan pabrik/PT, hotspot jemput karyawan pulang kerja."
  },
  {
    "id": "61",
    "date": "2025-12-17",
    "day": "Rabu",
    "time_window": "Malam",
    "predicted_hour": "20:00",
    "origin": "Apotek Al Fattah 2 Jalan Cingised",
    "type": "Bike Delivery",
    "category": "Health/Emergency",
    "lat": -6.9320,
    "lng": 107.6800,
    "zone": "Cisaranten - Cingised",
    "notes": "Pembelian obat sering terjadi di malam hari."
  },
  {
    "id": "69",
    "date": "2025-12-17",
    "day": "Rabu",
    "time_window": "Pagi",
    "predicted_hour": "07:30",
    "origin": "Toko Megaria Plastik Jalan Stasion Lama",
    "type": "Bike Delivery",
    "category": "Commercial",
    "lat": -6.9200,
    "lng": 107.6400,
    "zone": "Stasiun Kiaracondong",
    "notes": "Area stasiun sangat sibuk di jam keberangkatan pagi."
  },
  {
    "id": "78",
    "date": "2025-12-16",
    "day": "Senin",
    "time_window": "Pagi",
    "predicted_hour": "06:45",
    "origin": "SDN 103 Coblong Kota Bandung",
    "type": "Bike Delivery",
    "category": "Education",
    "lat": -6.8900,
    "lng": 107.6150,
    "zone": "Dago - Coblong",
    "notes": "Hotspot sekolah sangat spesifik di jam antar (06:30-07:00)."
  },
  {
    "id": "84",
    "date": "2025-12-15",
    "day": "Minggu",
    "time_window": "Siang",
    "predicted_hour": "10:00",
    "origin": "Lapas Sukamiskin Jalan A.H. Nasution",
    "type": "Bike",
    "category": "Gov/Facility",
    "lat": -6.9100,
    "lng": 107.6700,
    "zone": "Arcamanik - Sukamiskin",
    "notes": "Jam kunjungan fasilitas umum biasanya pagi menjelang siang."
  },
  {
    "id": "101",
    "date": "2025-12-10",
    "day": "Selasa",
    "time_window": "Sore",
    "predicted_hour": "15:00",
    "origin": "SMK Bina Warga Jalan Buah Batu (Turangga)",
    "type": "Bike",
    "category": "Education",
    "lat": -6.9420,
    "lng": 107.6230,
    "zone": "Buah Batu",
    "notes": "Jam pulang sekolah tingkat SMK/SMA."
  },
  {
    "id": "131",
    "date": "2025-12-07",
    "day": "Sabtu",
    "time_window": "Sore",
    "predicted_hour": "16:00",
    "origin": "Stasiun Kiaracondong (Jl Stasion Lama)",
    "type": "Bike",
    "category": "Transport Hub",
    "lat": -6.9200,
    "lng": 107.6400,
    "zone": "Stasiun Kiaracondong",
    "notes": "Kedatangan kereta ekonomi/lokal sering terjadi sore hari."
  },
  {
    "id": "145",
    "date": "2025-12-06",
    "day": "Jumat",
    "time_window": "Malam",
    "predicted_hour": "19:00",
    "origin": "Jatinangor Town Square",
    "type": "Bike",
    "category": "Mall/Lifestyle",
    "lat": -6.9320,
    "lng": 107.7700,
    "zone": "Jatinangor",
    "notes": "Pusat keramaian mahasiswa Jatinangor (Unpad/ITB/Ikopin) di malam hari."
  },
  {
    "id": "151",
    "date": "2025-12-06",
    "day": "Jumat",
    "time_window": "Malam",
    "predicted_hour": "20:00",
    "origin": "Trans Studio Mall Jalan Trans Studio",
    "type": "Bike",
    "category": "Mall/Lifestyle",
    "lat": -6.9250,
    "lng": 107.6360,
    "zone": "Gatot Subroto - TSM",
    "notes": "Jumat malam adalah peak hour bubaran mall."
  },
  {
    "id": "159",
    "date": "2025-12-05",
    "day": "Kamis",
    "time_window": "Siang",
    "predicted_hour": "12:30",
    "origin": "Mie Gacoan Cibiru Nasution",
    "type": "Bike",
    "category": "Culinary",
    "lat": -6.9200,
    "lng": 107.7150,
    "zone": "Cibiru",
    "notes": "Spot antrian panjang, sangat ramai saat makan siang."
  },
  {
    "id": "171",
    "date": "2025-12-03",
    "day": "Selasa",
    "time_window": "Pagi",
    "predicted_hour": "08:00",
    "origin": "AMP FK Unpad Jalan Sederhana III",
    "type": "Bike Delivery",
    "category": "Education/Office",
    "lat": -6.8900,
    "lng": 107.6000,
    "zone": "Sukajadi - Sederhana",
    "notes": "Aktivitas kampus/akademik pagi hari."
  },
  {
    "id": "202",
    "date": "2025-11-28",
    "day": "Jumat",
    "time_window": "Pagi",
    "predicted_hour": "07:30",
    "origin": "Perumahan Arcamanik Urban Living AULIV B23",
    "type": "Bike",
    "category": "Residential",
    "lat": -6.9200,
    "lng": 107.6800,
    "zone": "Arcamanik",
    "notes": "Warga berangkat kerja dari perumahan."
  },
  {
    "id": "228",
    "date": "2025-11-17",
    "day": "Minggu",
    "time_window": "Malam",
    "predicted_hour": "19:00",
    "origin": "Mie Gacoan Gatsu Jalan Pelajar Pejuang 45",
    "type": "Bike",
    "category": "Culinary",
    "lat": -6.9350,
    "lng": 107.6300,
    "zone": "Lengkong - Gatsu",
    "notes": "Spot kuliner populer, Minggu malam sangat padat."
  },
  {
    "id": "233",
    "date": "2025-11-11",
    "day": "Senin",
    "time_window": "Sore",
    "predicted_hour": "16:00",
    "origin": "Bandung National Institute of Technology (Itenas)",
    "type": "Bike",
    "category": "Education",
    "lat": -6.9000,
    "lng": 107.6350,
    "zone": "Suci - Itenas",
    "notes": "Jam bubaran kuliah sore."
  },
  {
    "id": "234",
    "date": "2025-11-10",
    "day": "Minggu",
    "time_window": "Pagi",
    "predicted_hour": "05:00",
    "origin": "Ud Sutrisno - Pasar Caringin",
    "type": "Bike",
    "category": "Market",
    "lat": -6.9350,
    "lng": 107.5750,
    "zone": "Caringin",
    "notes": "Aktivitas pasar tradisional/induk pagi buta."
  }
];

export const DAYS_INDONESIA = [
  'Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'
];

export const CATEGORY_COLORS: Record<string, string> = {
  // 🔴 Food/Culinary: Red
  'Culinary': '#FF5252', 
  'Culinary Night': '#D32F2F',

  // 🔵 Bike/Passenger: Cyan
  'Bike': '#18FFFF', 
  'Bike Delivery': '#00E5FF',

  // 🟢 Logistics: Neon Green
  'Logistics': '#69F0AE',

  // 🟡 Money/Profit/Commercial: Gold
  'Commercial': '#FFD740',
  'Market': '#FFC107',
  'Mall/Lifestyle': '#FFAB00',
  
  // Others
  'Residential': '#FF6E40', // Deep Orange
  'Residential/Shop': '#FF9E80',
  'Education': '#7C4DFF', // Deep Purple
  'Education/Office': '#651FFF',
  'Health': '#00E676', // Green
  'Health/Office': '#00C853',
  'Health/Emergency': '#00B8D4',
  'Industrial/Office': '#B0BEC5',
  'Service': '#90A4AE',
  'Service/Hangout': '#78909C',
  'Gov/Facility': '#607D8B',
  'Transport Hub': '#40C4FF',
  'Other': '#EEEEEE'
};